python3 /Users/mr.cheng/Documents/我的项目/email-subscribe/xiaoxiao.py
python3 /Users/mr.cheng/Documents/我的项目/email-subscribe/wait.py
python3 /Users/mr.cheng/Documents/我的项目/email-subscribe/jwen.py
python3 /Users/mr.cheng/Documents/我的项目/email-subscribe/wait.py
python3 /Users/mr.cheng/Documents/我的项目/email-subscribe/peter.py
python3 /Users/mr.cheng/Documents/我的项目/email-subscribe/wait.py
python3 /Users/mr.cheng/Documents/我的项目/email-subscribe/xiaojiejie.py
python3 /Users/mr.cheng/Documents/我的项目/email-subscribe/wait.py
python3 /Users/mr.cheng/Documents/我的项目/email-subscribe/beibei.py
